services:
  loki:
    image: grafana/loki:3.7.1
    container_name: sail-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:13.0.1
    container_name: sail-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./topology:/topology                        # Ansible writes here
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
      - HTTP_PROXY=http://10.93.144.53:8080
      - HTTPS_PROXY=http://10.93.144.53:8080
      - NO_PROXY=localhost,127.0.0.1,sail-loki,sail-fileserver,10.202.52.0/24
    restart: unless-stopped
    depends_on:
      - loki

  fileserver:
    image: nginx:alpine
    container_name: sail-fileserver
    volumes:
      - ./topology:/usr/share/nginx/html:rw
    ports:
      - "8880:80"
    restart: unless-stopped
    entrypoint: >
      sh -c '[ -f /usr/share/nginx/html/topology.json ] ||
      echo "{\"nodes\":[],\"edges\":[]}" > /usr/share/nginx/html/topology.json
      && nginx -g "daemon off;"'