services:

  sail-app:
    build: .
    container_name: sail-app
    ports:
      - "8880:8880"
    volumes:
      - ./topology:/data:rw
    environment:
      - DATA_DIR=/data
      - MAX_HISTORY_ENTRIES=1000
      - LOKI_URL=http://sail-loki:3100
      - NO_PROXY=localhost,127.0.0.1,sail-loki,10.202.52.0/24
      - no_proxy=localhost,127.0.0.1,sail-loki,10.202.52.0/24
    restart: unless-stopped

  loki:
    image: grafana/loki:3.7.1
    container_name: sail-loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped